In [1]:
! python --version

Python 3.9.12


In [6]:
for i in range(1500,2700):
    if i%35==0:
        print(str(i)+"\n")

1505

1540

1575

1610

1645

1680

1715

1750

1785

1820

1855

1890

1925

1960

1995

2030

2065

2100

2135

2170

2205

2240

2275

2310

2345

2380

2415

2450

2485

2520

2555

2590

2625

2660

2695



In [8]:
x=int(input("enter fernhit:"))
print("celisies temp is"+str(5*(x-32/9)))

enter fernhit:5
celisies temp is7.222222222222223


In [16]:
for x in range(5):
        print('*'*x)
for x in range(5):
        print('*'*(5-x))


*
**
***
****
*****
****
***
**
*


In [27]:
x=input("enter word:")
print(x[::-1])

enter word:google
elgoog


In [32]:
num1=int(input("enter num1:"))
num2=int(input("enter num2:"))
num3=int(input("enter num3:"))
if num1>num2:
    if num1>num3:
        print(num1)
    else:
        print(num3)
else:
    if num2>num3:
        print(num2)
    else:
        print(num3)

enter num1:2
enter num2:3
enter num3:1
3


In [43]:
def func(x):
    sum=0
    for i in x:
        sum+=i
    return sum

In [44]:
print(func({1,2,3,4,5}))

15


In [46]:
for x in range(0,6):
    if x==3 or x==6:
        continue
    print(x)

0
1
2
4
5


In [53]:
def func(x):
    sum=1
    for i in range(1,x+1):
        sum*=i
    return sum

In [54]:
print(func(4))

24


In [1]:
x=lambda a,b:a*b
print(x(5,6))

30


In [3]:
import myLib as lib
lib.funcc(3)

6

In [4]:
import myLib
a=['harry botter','embedded','ai','kosa']
b=myLib.Libarary(a,'ashraf')
while(1):
    print('1-DisplayBooks\n2-LendBook\n3-AddBook\n4-ReturnBook\n5-exit')
    z=int(input())
    if z==1:
        b.DisplayBooks()
    elif z==2:
        book=input('enter book name:')
        name=input('enter ur name:')
        b.LendBook(book,name)
    elif z==3:
        book=input('enter book name:')
        b.AddBook(book)
    elif z==4:
        book=input('enter book name:')
        b.ReturnBook(book)
    else:
        break

1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
1
['harry botter', 'embedded', 'ai', 'kosa']
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
2
enter book name:harry botter
enter ur name:medo
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
1
['embedded', 'ai', 'kosa']
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
3
enter book name:seko
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
1
['embedded', 'ai', 'kosa', 'seko']
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
4
enter book name:harry botter
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
1
['embedded', 'ai', 'kosa', 'seko', 'harry botter']
1-DisplayBooks
2-LendBook
3-AddBook
4-ReturnBook
5-exit
5


In [19]:
from bs4 import BeautifulSoup

In [30]:
import csv
csv_file=open("youtube channals.csv",'w',encoding='utf-8')
writer=csv.writer(csv_file)
writer.writerow(['name','photo'])

12

In [31]:
file=open('Channel list-YouTube.html',encoding='utf-8') 

In [32]:
soup=BeautifulSoup(file,'lxml')
type(soup)

bs4.BeautifulSoup

In [34]:
articles=soup.find_all('div',{'id':'content-section','class':'style-scope ytd-channel-renderer'})
for article in articles:
    name=article.find('yt-formatted-string',class_='style-scope ytd-channel-name').text
    photo=article.find('img',class_='style-scope yt-img-shadow').attrs['src']
    writer.writerow([name,photo])


In [24]:
type(article)
#print(article.prettify())

bs4.element.Tag

In [1]:
# import webdriver
from selenium import webdriver

# create webdriver object
driver = webdriver.Chrome()

# get geeksforgeeks.org
driver.get("https://www.geeksforgeeks.org/")

# get page_source
print(driver.page_source)


SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 93
Current browser version is 105.0.5195.102 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00FDD403+2479107]
	Ordinal0 [0x00F77D51+2063697]
	Ordinal0 [0x00E820C8+1056968]
	Ordinal0 [0x00EA043A+1180730]
	Ordinal0 [0x00E9C355+1164117]
	Ordinal0 [0x00E99B7F+1153919]
	Ordinal0 [0x00EC9CBF+1350847]
	Ordinal0 [0x00EC992A+1349930]
	Ordinal0 [0x00EC583B+1333307]
	Ordinal0 [0x00EA1F94+1187732]
	Ordinal0 [0x00EA2DE9+1191401]
	GetHandleVerifier [0x0115F3F6+1531734]
	GetHandleVerifier [0x0120E9AE+2249998]
	GetHandleVerifier [0x010639AB+501003]
	GetHandleVerifier [0x01062A29+497033]
	Ordinal0 [0x00F7D11D+2085149]
	Ordinal0 [0x00F811C8+2101704]
	Ordinal0 [0x00F81302+2102018]
	Ordinal0 [0x00F8AA71+2140785]
	BaseThreadInitThunk [0x76BEFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77557A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77557A6E+238]


In [2]:
'x' in globals()


False

In [9]:
aa='apple'
b=aa.replace('pp','bb')
print(b)

abble


In [10]:
items = {'item1' : 1 , 'item2' : 2 , 'item3' : 3}
for item in items:
    print(item)

item1
item2
item3


In [58]:
import pandas as pd

In [2]:
import numpy as np


In [3]:
np.array([1,2,3])


array([1, 2, 3])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.random.random((4,4))

array([[0.14726432, 0.15700298, 0.59478184, 0.97819137],
       [0.13594335, 0.3220378 , 0.88071374, 0.5704776 ],
       [0.20293209, 0.60948194, 0.23683338, 0.58327986],
       [0.751865  , 0.95758622, 0.19428951, 0.53118182]])

In [12]:
a=np.array([1,2,3,4,5])

In [13]:
a=np.append(a,7)

In [14]:
a


array([1, 2, 3, 4, 5, 7])

In [16]:
np.max(a)

7

In [17]:
a=np.random.randint(0,10,(4,4))

In [18]:
a

array([[8, 4, 6, 4],
       [3, 7, 2, 0],
       [7, 2, 1, 2],
       [9, 6, 7, 2]])

In [26]:
np.split(a,a.shape[0])

[array([[8, 4, 6, 4]]),
 array([[3, 7, 2, 0]]),
 array([[7, 2, 1, 2]]),
 array([[9, 6, 7, 2]])]

In [52]:
a=np.array([1,2,3,4,5])

In [53]:
a.shape

(5,)

In [54]:
a=a[np.newaxis,:]

In [55]:
a.shape

(1, 5)

In [56]:
a

array([[1, 2, 3, 4, 5]])

In [57]:
np.sort(a,axis=1)

array([[1, 2, 3, 4, 5]])

In [109]:
df=pd.read_csv('BankChurners.csv')

In [110]:
df.dtypes

CLIENTNUM                                                                                                                               int64
Attrition_Flag                                                                                                                         object
Customer_Age                                                                                                                            int64
Gender                                                                                                                                 object
Dependent_count                                                                                                                         int64
Education_Level                                                                                                                        object
Marital_Status                                                                                                                         object
Income

In [111]:
df=df.iloc[:500,:5]

In [112]:
df.to_csv('sample.csv')

In [113]:
df=pd.read_csv('sample.csv',header=None,names=['cust_no','celentum','atf','ca','g','d'])

In [114]:
df

cust_no   celentum                atf            ca       g  \
0        NaN  CLIENTNUM     Attrition_Flag  Customer_Age  Gender   
1        0.0  768805383  Existing Customer            45       M   
2        1.0  818770008  Existing Customer            49       F   
3        2.0  713982108  Existing Customer            51       M   
4        3.0  769911858  Existing Customer            40       F   
..       ...        ...                ...           ...     ...   
496    495.0  716920908  Existing Customer            52       M   
497    496.0  708095133  Existing Customer            43       M   
498    497.0  711195558  Existing Customer            59       M   
499    498.0  772735758  Existing Customer            44       M   
500    499.0  712024908  Existing Customer            56       F   

                   d  
0    Dependent_count  
1                  3  
2                  5  
3                  3  
4                  4  
..               ...  
496                4  
497                4  
498                1  
499                1  
500                1  

[501 rows x 6 columns]

In [115]:
df.columns=df.iloc[0]

In [116]:
df=df.iloc[1:]

In [117]:
df

0      NaN  CLIENTNUM     Attrition_Flag Customer_Age Gender Dependent_count
1      0.0  768805383  Existing Customer           45      M               3
2      1.0  818770008  Existing Customer           49      F               5
3      2.0  713982108  Existing Customer           51      M               3
4      3.0  769911858  Existing Customer           40      F               4
5      4.0  709106358  Existing Customer           40      M               3
..     ...        ...                ...          ...    ...             ...
496  495.0  716920908  Existing Customer           52      M               4
497  496.0  708095133  Existing Customer           43      M               4
498  497.0  711195558  Existing Customer           59      M               1
499  498.0  772735758  Existing Customer           44      M               1
500  499.0  712024908  Existing Customer           56      F               1

[500 rows x 6 columns]

In [118]:
df.filter(regex='g$',axis=1)

0       Attrition_Flag
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Existing Customer
5    Existing Customer
..                 ...
496  Existing Customer
497  Existing Customer
498  Existing Customer
499  Existing Customer
500  Existing Customer

[500 rows x 1 columns]

In [97]:
df.drop('Attrition_Flag',inplace=True,axis=1)

C:\Users\user\AppData\Local\Temp\ipykernel_220\307464358.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Attrition_Flag',inplace=True,axis=1)


In [119]:
df


0      NaN  CLIENTNUM     Attrition_Flag Customer_Age Gender Dependent_count
1      0.0  768805383  Existing Customer           45      M               3
2      1.0  818770008  Existing Customer           49      F               5
3      2.0  713982108  Existing Customer           51      M               3
4      3.0  769911858  Existing Customer           40      F               4
5      4.0  709106358  Existing Customer           40      M               3
..     ...        ...                ...          ...    ...             ...
496  495.0  716920908  Existing Customer           52      M               4
497  496.0  708095133  Existing Customer           43      M               4
498  497.0  711195558  Existing Customer           59      M               1
499  498.0  772735758  Existing Customer           44      M               1
500  499.0  712024908  Existing Customer           56      F               1

[500 rows x 6 columns]

In [120]:
def gender(row):
    if row=='M':
        return 'male'
    elif row=='F':
        return 'female'

In [121]:
df['Gender']=df['Gender'].apply(gender)

C:\Users\user\AppData\Local\Temp\ipykernel_220\1283500417.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender']=df['Gender'].apply(gender)


In [122]:
df

0      NaN  CLIENTNUM     Attrition_Flag Customer_Age  Gender Dependent_count
1      0.0  768805383  Existing Customer           45    male               3
2      1.0  818770008  Existing Customer           49  female               5
3      2.0  713982108  Existing Customer           51    male               3
4      3.0  769911858  Existing Customer           40  female               4
5      4.0  709106358  Existing Customer           40    male               3
..     ...        ...                ...          ...     ...             ...
496  495.0  716920908  Existing Customer           52    male               4
497  496.0  708095133  Existing Customer           43    male               4
498  497.0  711195558  Existing Customer           59    male               1
499  498.0  772735758  Existing Customer           44    male               1
500  499.0  712024908  Existing Customer           56  female               1

[500 rows x 6 columns]

In [131]:
df=df.drop_duplicates('Customer_Age',keep='last')

In [133]:
df.isna().sum()

0
NaN                0
CLIENTNUM          0
Attrition_Flag     0
Customer_Age       0
Gender             0
Dependent_count    0
dtype: int64

In [134]:
df['Attrition_Flag'].value_counts()

Existing Customer    36
Attrited Customer     2
Name: Attrition_Flag, dtype: int64

In [136]:
df.drop('NaN',inplace=True,axis=1)

KeyError: "['NaN'] not found in axis"

In [137]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[1 2 3 4 5 6]


In [138]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [139]:
arr

array([1, 2, 3])

In [140]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df['C'] = df.apply(lambda row: row['A'] + row['B'], axis=1)
df.values

array([[1, 4, 5],
       [2, 5, 7],
       [3, 6, 9]], dtype=int64)

In [141]:
import os


In [142]:
os.getcwd()

'C:\\Users\\user'

In [143]:
os.listdir()

['.android',
 '.bash_history',
 '.conda',
 '.condarc',
 '.continuum',
 '.dbus-keyrings',
 '.eclipse',
 '.fontconfig',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.mchp_packs',
 '.mplabcomm',
 '.p2',
 '.VirtualBox',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'BankChurners.csv',
 'chromedriver.exe',
 'Contacts',
 'Cookies',
 'd4ac4633ebd6440fa397b84f1bc94a3c.7z',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'first session.ipynb',
 'FoundryAnalytics',
 'Heaven',
 'inittk.ini',
 'inst.ini',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'MPLABXProjects',
 'Music',
 'My Documents',
 'myLib.py',
 'NetHood',
 'New folder',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms

In [144]:
import sys

In [145]:
import matplotlib.pyplot as plt 

In [3]:
import numpy as np
import cv2

In [2]:
from sklearn import linear_model

In [1]:
x=1
y=x
y=2
print(x,y)

1 2


In [2]:
x=[1,2,3]
y=x
y=[2,3,4]
print(x,y)

[1, 2, 3] [2, 3, 4]


In [7]:
z=[x,x,x]
x=[2,3,4]
print(z)

[[2, 3, 4], [2, 3, 4], [2, 3, 4]]


In [8]:
y=x.copy()
y[0]=5
print(x,y)

[2, 3, 4] [5, 3, 4]


In [10]:
print('   /|')
print('  / |')
print(' /  |')
print('/___|')

   /|
  / |
 /  |
/___|


In [11]:
character_name='mohamad'
character_age=22
print('there once was a man named',character_name,',')
print('he was',character_age,'years old.')

character_name='ahmed'
print('he really like the name',character_name,',')
print('but didn\'t like being',character_age,'.')



there once was a man named mohamad ,
he was 22 years old.
he really like the name ahmed ,
but didn't like being 22 .


In [13]:
phrase='giraffe academy'
print(phrase.replace('giraffe','eleliphant'))

eleliphant academy


In [14]:
name=input('enter ur name: ')
print('hello',name,'!')

enter ur name: mohamad
hello mohamad !


In [15]:
num1=int(input('enter num1: '))
num2=int(input('enter num2: '))
print(num1+num2)

enter num1: 2
enter num2: 5
7


In [16]:
color=input('enter a color: ')
plural_noun=input('enter a plural_noun: ')
celebrity=input('enter a celebrity: ')
print(f'rose are {color}')
print(f'{plural_noun} are blue')
print(f'I love {celebrity}')

enter a color: magenta
enter a plural_noun: microwaves
enter a celebrity: tom hanks
rose are magenta
microwaves are blue
I love tom hanks


In [18]:
def say_hi(name,age):
    print('hello',name,'!','you are',age,'years old.')
say_hi('mohamad',22)

hello mohamad ! you are 22 years old.


In [19]:
def cube(num):
    return num*num*num
print(cube(3))

27


In [20]:
is_male=False
is_tall=False
if is_male and is_tall:
    print('u r a tall man')
elif not(is_male) and is_tall:
    print('u r a tall woman')
elif is_male and not(is_tall):
    print('u r a short man')
else:
    print('u r a short woman')


u r a short woman


In [22]:
def max_num(num1,num2,num3):
    if num1>=num2 and num1>=num3:
        return num1
    elif num2>=num1 and num2>=num3:
        return num2
    else:
        return num3
print(max_num(5,2,3))


5


In [23]:
num1=int(input('enter num1: '))
operator=input('enter operator: ')
num2=int(input('enter num2: '))
if operator=='+':
    print(num1+num2)
elif operator=='-':
    print(num1-num2)
elif operator=='*':
    print(num1*num2)
elif operator=='/':
    print(num1/num2)
else:
    print('invalid operator')


enter num1: 5
enter operator: +
enter num2: 6
11


In [26]:
mount_conversion={
    'jan':'january',
    'feb':'february',
    'mar':'march',
    'apr':'april',
    'may':'may',
    'jun':'june',
    'jul':'july',
    'aug':'august',
    'sep':'september',
    'oct':'october',
    'nov':'november',
    'dec':'december'    
}
print(mount_conversion.get('mag','not a valid key'))

not a valid key


In [27]:
i=1
while i<=10:
    print(i)
    i+=1
print('done with loop')

1
2
3
4
5
6
7
8
9
10
done with loop


In [30]:
guess=''
secret_word='giraffe'
out_of_guesses=False
guess_limit=3
guess_count=0
while guess!=secret_word and not(out_of_guesses):
    if guess_count<guess_limit:
        guess=input('enter guess: ')
        guess_count+=1
    else:
        out_of_guesses=True
if out_of_guesses:
    print('game ovar')
else:
    print('you win')

enter guess: giraffe
you win


In [31]:
friends=['mohamad','ahmed','nader']
for friend in friends:
    print(friend)

mohamad
ahmed
nader


In [32]:
def raise_to_power(base_num,power_num):
    result=1
    for index in range(power_num):
        result*=base_num
    return result
print(raise_to_power(2,3))

8


In [33]:
number_grid=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [0]
]
for row in number_grid:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9
0


In [37]:
def translate(phrase):
    translation=''
    for letter in phrase:
        if letter.lower() in 'aeoui':
            if letter.isupper():
                translation=translation+'G'
            else:
                translation=translation+'g'
        else:
            translation=translation+letter
    return translation
print(translate(input('enter phrase: ')))

enter phrase: sdf
sdf


In [40]:
try:
#    value=10/0
    number=int(input('enter num: '))
    print(number)
except ZeroDivisionError:
    print('ZeroDivisionError')
except ValueError:
    print('ValueError')


enter num: a
ValueError


In [41]:
employee_file=open('employees.txt','r')
for employee in employee_file.readlines():
    print(employee)
employee_file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'employees.txt'

In [43]:
import useful_tools
print(useful_tools.roll_dice(10))

7


In [44]:
from Student import Student
student1=Student('mohamad','mechatronics',3.3,False)
print(student1.name)

mohamad


In [49]:
from Question import Question
question_prompts=[
    'what color are apples\n(a) Red/Green\n(b) Purble\n(c) Orange\n\n',
    'what color are bananas\n(a) Teal\n(b) Magenta\n(c) Yellow\n\n',
    'what color are strewberries\n(a) Yellow\n(b) Red\n(c) Blue\n\n'
]

questions=[
    Question(question_prompts[0],'a'),
    Question(question_prompts[1],'c'),
    Question(question_prompts[2],'b')    
]

def run_test(questions):
    score=0
    for question in questions:
        answer=input(question.prompt)
        if answer ==question.answer:
            score+=1
    print('you got',str(score),'/',str(len(question_prompts)),'correct')

run_test(questions)

what color are apples
(a) Red/Green
(b) Purble
(c) Orange

c
what color are bananas
(a) Teal
(b) Magenta
(c) Yellow

c
what color are strewberries
(a) Yellow
(b) Red
(c) Blue

b
you got 2 / 3 correct


In [1]:
import numpy as np
import math


In [7]:
T_MAX = 150
time_steps = np.arange(T_MAX)
w = np.multiply(0.3, np.ones(T_MAX))
print(w)

[0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.3]


In [10]:
M = 50
N = 60
true_map = np.zeros((M, N))
true_map[0:10, 0:10] = 1
true_map[30:35, 40:45] = 1
true_map[3:6,40:60] = 1;
true_map[20:30,25:29] = 1;
true_map[40:50,5:25] = 1;

# Initialize the belief map.
# We are assuming a uniform prior.
m = np.multiply(0.5, np.ones((M, N)))

# Initialize the log odds ratio.
L0 = np.log(np.divide(m, np.subtract(1, m)))
print(L0)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
import numpy as np
import math
import matplotlib.pyplot as plt
import matplotlib.animation as anim
from IPython.display import HTML

In [12]:
# Calculates the inverse measurement model for a laser scanner.
# It identifies three regions. The first where no information is available occurs
# outside of the scanning arc. The second where objects are likely to exist, at the
# end of the range measurement within the arc. The third are where objects are unlikely
# to exist, within the arc but with less distance than the range measurement.
def inverse_scanner(num_rows, num_cols, x, y, theta, meas_phi, meas_r, rmax, alpha, beta):
    m = np.zeros((M, N))
    for i in range(num_rows):
        for j in range(num_cols):
            # Find range and bearing relative to the input state (x, y, theta).
            r = math.sqrt((i - x)**2 + (j - y)**2)
            phi = (math.atan2(j - y, i - x) - theta + math.pi) % (2 * math.pi) - math.pi
            
            # Find the range measurement associated with the relative bearing.
            k = np.argmin(np.abs(np.subtract(phi, meas_phi)))
            
            # If the range is greater than the maximum sensor range, or behind our range
            # measurement, or is outside of the field of view of the sensor, then no
            # new information is available.
            if (r > min(rmax, meas_r[k] + alpha / 2.0)) or (abs(phi - meas_phi[k]) > beta / 2.0):
                m[i, j] = 0.5
            
            # If the range measurement lied within this cell, it is likely to be an object.
            elif (meas_r[k] < rmax) and (abs(r - meas_r[k]) < alpha / 2.0):
                m[i, j] = 0.7
            
            # If the cell is in front of the range measurement, it is likely to be empty.
            elif r < meas_r[k]:
                m[i, j] = 0.3
                
    return m
                            

In [13]:
# Generates range measurements for a laser scanner based on a map, vehicle position,
# and sensor parameters.
# Uses the ray tracing algorithm.
def get_ranges(true_map, X, meas_phi, rmax):
    (M, N) = np.shape(true_map)
    x = X[0]
    y = X[1]
    theta = X[2]
    meas_r = rmax * np.ones(meas_phi.shape)
    
    # Iterate for each measurement bearing.
    for i in range(len(meas_phi)):
        # Iterate over each unit step up to and including rmax.
        for r in range(1, rmax+1):
            # Determine the coordinates of the cell.
            xi = int(round(x + r * math.cos(theta + meas_phi[i])))
            yi = int(round(y + r * math.sin(theta + meas_phi[i])))
            
            # If not in the map, set measurement there and stop going further.
            if (xi <= 0 or xi >= M-1 or yi <= 0 or yi >= N-1):
                meas_r[i] = r
                break
            # If in the map, but hitting an obstacle, set the measurement range
            # and stop ray tracing.
            elif true_map[int(round(xi)), int(round(yi))] == 1:
                meas_r[i] = r
                break
                
    return meas_r

In [14]:
# Simulation time initialization.
T_MAX = 150
time_steps = np.arange(T_MAX)

# Initializing the robot's location.
x_0 = [30, 30, 0]

# The sequence of robot motions.
u = np.array([[3, 0, -3, 0], [0, 3, 0, -3]])
u_i = 1

# Robot sensor rotation command
w = np.multiply(0.3, np.ones(len(time_steps)))

# True map (note, columns of map correspond to y axis and rows to x axis, so 
# robot position x = x(1) and y = x(2) are reversed when plotted to match
M = 50
N = 60
true_map = np.zeros((M, N))
true_map[0:10, 0:10] = 1
true_map[30:35, 40:45] = 1
true_map[3:6,40:60] = 1;
true_map[20:30,25:29] = 1;
true_map[40:50,5:25] = 1;

# Initialize the belief map.
# We are assuming a uniform prior.
m = np.multiply(0.5, np.ones((M, N)))

# Initialize the log odds ratio.
L0 = np.log(np.divide(m, np.subtract(1, m)))
L = L0

# Parameters for the sensor model.
meas_phi = np.arange(-0.4, 0.4, 0.05)
rmax = 30 # Max beam range.
alpha = 1 # Width of an obstacle (distance about measurement to fill in).
beta = 0.05 # Angular width of a beam.

# Initialize the vector of states for our simulation.
x = np.zeros((3, len(time_steps)))
x[:, 0] = x_0



In [15]:
%%capture
# Intitialize figures.
map_fig = plt.figure()
map_ax = map_fig.add_subplot(111)
map_ax.set_xlim(0, N)
map_ax.set_ylim(0, M)

invmod_fig = plt.figure()
invmod_ax = invmod_fig.add_subplot(111)
invmod_ax.set_xlim(0, N)
invmod_ax.set_ylim(0, M)

belief_fig = plt.figure()
belief_ax = belief_fig.add_subplot(111)
belief_ax.set_xlim(0, N)
belief_ax.set_ylim(0, M)

meas_rs = []
meas_r = get_ranges(true_map, x[:, 0], meas_phi, rmax)
meas_rs.append(meas_r)
invmods = []
invmod = inverse_scanner(M, N, x[0, 0], x[1, 0], x[2, 0], meas_phi, meas_r, \
                         rmax, alpha, beta)
invmods.append(invmod)
ms = []
ms.append(m)

# Main simulation loop.
for t in range(1, len(time_steps)):
    # Perform robot motion.
    move = np.add(x[0:2, t-1], u[:, u_i]) 
    # If we hit the map boundaries, or a collision would occur, remain still.
    if (move[0] >= M - 1) or (move[1] >= N - 1) or (move[0] <= 0) or (move[1] <= 0) \
        or true_map[int(round(move[0])), int(round(move[1]))] == 1:
        x[:, t] = x[:, t-1]
        u_i = (u_i + 1) % 4
    else:
        x[0:2, t] = move
    x[2, t] = (x[2, t-1] + w[t]) % (2 * math.pi)
    
    # TODO Gather the measurement range data, which we will convert to occupancy probabilities
    # using our inverse measurement model.
    # meas_r = ...
    meas_rs.append(meas_r)
    
    # TODO Given our range measurements and our robot location, apply our inverse scanner model
    # to get our measure probabilities of occupancy.
    # invmod = ...
    invmods.append(invmod)
    
    # TODO Calculate and update the log odds of our occupancy grid, given our measured
    # occupancy probabilities from the inverse model.
    # L = ...
    
    # TODO Calculate a grid of probabilities from the log odds.
    # m = ...
    ms.append(m)
    


In [16]:
# Ouput for grading. Do not modify this code!
m_f = ms[-1]

print("{}".format(m_f[40, 10]))
print("{}".format(m_f[30, 40]))
print("{}".format(m_f[35, 40]))
print("{}".format(m_f[0, 50]))
print("{}".format(m_f[10, 5]))
print("{}".format(m_f[20, 15]))
print("{}".format(m_f[25, 50]))  

0.5
0.5
0.5
0.5
0.5
0.5
0.5


In [17]:
def map_update(i):
    map_ax.clear()
    map_ax.set_xlim(0, N)
    map_ax.set_ylim(0, M)
    map_ax.imshow(np.subtract(1, true_map), cmap='gray', origin='lower', vmin=0.0, vmax=1.0)
    x_plot = x[1, :i+1]
    y_plot = x[0, :i+1]
    map_ax.plot(x_plot, y_plot, "bx-")

def invmod_update(i):
    invmod_ax.clear()
    invmod_ax.set_xlim(0, N)
    invmod_ax.set_ylim(0, M)
    invmod_ax.imshow(invmods[i], cmap='gray', origin='lower', vmin=0.0, vmax=1.0)
    for j in range(len(meas_rs[i])):
        invmod_ax.plot(x[1, i] + meas_rs[i][j] * math.sin(meas_phi[j] + x[2, i]), \
                       x[0, i] + meas_rs[i][j] * math.cos(meas_phi[j] + x[2, i]), "ko")
    invmod_ax.plot(x[1, i], x[0, i], 'bx')
    
def belief_update(i):
    belief_ax.clear()
    belief_ax.set_xlim(0, N)
    belief_ax.set_ylim(0, M)
    belief_ax.imshow(ms[i], cmap='gray', origin='lower', vmin=0.0, vmax=1.0)
    belief_ax.plot(x[1, max(0, i-10):i], x[0, max(0, i-10):i], 'bx-')
    
map_anim = anim.FuncAnimation(map_fig, map_update, frames=len(x[0, :]), repeat=False)
invmod_anim = anim.FuncAnimation(invmod_fig, invmod_update, frames=len(x[0, :]), repeat=False)
belief_anim = anim.FuncAnimation(belief_fig, belief_update, frames=len(x[0, :]), repeat=False)


In [18]:
HTML(map_anim.to_html5_video())

RuntimeError: Requested MovieWriter (ffmpeg) not available

In [19]:
HTML(invmod_anim.to_html5_video())

RuntimeError: Requested MovieWriter (ffmpeg) not available

In [20]:
HTML(belief_anim.to_html5_video())

RuntimeError: Requested MovieWriter (ffmpeg) not available

In [ ]:
def solution(area):
    output=[]
    while area!=0:
        for i in range(1:1000):
            if (i*i)>area:
                output.append(i)
                area-=(i*i)
                break
    print(output)
    

In [ ]:
solution(12)

In [13]:
# -----------
# User Instructions:
#
# Modify the the search function so that it returns
# a shortest path as follows:
# 
# [['>', 'v', ' ', ' ', ' ', ' '],
#  [' ', '>', '>', '>', '>', 'v'],
#  [' ', ' ', ' ', ' ', ' ', 'v'],
#  [' ', ' ', ' ', ' ', ' ', 'v'],
#  [' ', ' ', ' ', ' ', ' ', '*']]
#
# Where '>', '<', '^', and 'v' refer to right, left, 
# up, and down motions. Note that the 'v' should be 
# lowercase. '*' should mark the goal cell.
#
# You may assume that all test cases for this function
# will have a path from init to goal.
# ----------

grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0]]
init = [0, 0]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['v','>' , '^', '<']

def search(grid,init,goal,cost):
    # ----------------------------------------
    # modify code below
    # ----------------------------------------
    closed = [[0 for row in range(len(grid[0]))] for col in range(len(grid))]
    closed[init[0]][init[1]] = 1
    expand = [[' ' for row in range(len(grid[0]))] for col in range(len(grid))]
    gFUNC = [[-1 for row in range(len(grid[0]))] for col in range(len(grid))]

    x = init[0]
    y = init[1]
    g = 0

    open = [[g, x, y]]

    found = False  # flag that is set when search is complete
    resign = False # flag set if we can't find expand

    while not found and not resign:
        if len(open) == 0:
            resign = True
            return 'fail'
        else:
            open.sort()
            open.reverse()
            next = open.pop()
            x = next[1]
            y = next[2]
            g = next[0]
            
            if x == goal[0] and y == goal[1]:
                expand[x][y]='*'
                while x!=init[0] or y!=init[1]:
                    for i in range(len(delta)):
                        x2 = x + delta[i][0]
                        y2 = y + delta[i][1]
                        if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                            if closed[x2][y2] == 1 and g>gFUNC[x2][y2]:
                                g = gFUNC[x2][y2]
                                x=x2
                                y=y2
                                expand[x][y] = delta_name[i]

                found = True
            else:
                for i in range(len(delta)):
                    x2 = x + delta[i][0]
                    y2 = y + delta[i][1]
                    if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                        if closed[x2][y2] == 0 and grid[x2][y2] == 0:
                            g2 = g + cost
                            open.append([g2, x2, y2])
                            closed[x2][y2] = 1
                            gFUNC[x2][y2] = g

    return expand # make sure you return the shortest path
search(grid,init,goal,cost)

[['>', 'v', ' ', ' ', ' ', ' '],
 [' ', '>', '>', '>', '>', 'v'],
 [' ', ' ', ' ', ' ', ' ', 'v'],
 [' ', ' ', ' ', ' ', ' ', 'v'],
 [' ', ' ', ' ', ' ', ' ', '*']]

In [3]:
grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0]]
print(len(grid))

5


In [8]:
# -----------
# User Instructions:
#
# Modify the the search function so that it returns
# a shortest path as follows:
# 
# [['>', 'v', ' ', ' ', ' ', ' '],
#  [' ', '>', '>', '>', '>', 'v'],
#  [' ', ' ', ' ', ' ', ' ', 'v'],
#  [' ', ' ', ' ', ' ', ' ', 'v'],
#  [' ', ' ', ' ', ' ', ' ', '*']]
#
# Where '>', '<', '^', and 'v' refer to right, left, 
# up, and down motions. Note that the 'v' should be 
# lowercase. '*' should mark the goal cell.
#
# You may assume that all test cases for this function
# will have a path from init to goal.
# ----------

grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0],
        [0, 0, 1, 0, 1, 0]]
init = [0, 0]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['^', '<', 'v', '>']

def search(grid,init,goal,cost):
    # ----------------------------------------
    # modify code below
    # ----------------------------------------
    closed = [[0 for row in range(len(grid[0]))] for col in range(len(grid))]
    closed[init[0]][init[1]] = 1

    x = init[0]
    y = init[1]
    g = 0

    open = [[g, x, y]]

    found = False  # flag that is set when search is complete
    resign = False # flag set if we can't find expand

    while not found and not resign:
        if len(open) == 0:
            resign = True
            return 'fail'
        else:
            open.sort()
            open.reverse()
            next = open.pop()
            x = next[1]
            y = next[2]
            g = next[0]
            
            if x == goal[0] and y == goal[1]:
                found = True
            else:
                for i in range(len(delta)):
                    x2 = x + delta[i][0]
                    y2 = y + delta[i][1]
                    if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                        if closed[x2][y2] == 0 and grid[x2][y2] == 0:
                            g2 = g + cost
                            open.append([g2, x2, y2])
                            closed[x2][y2] = 1

    return closed # make sure you return the shortest path
search(grid,init,goal,cost)

[[1, 1, 0, 1, 1, 1],
 [1, 1, 1, 1, 1, 1],
 [1, 1, 0, 1, 0, 1],
 [1, 1, 0, 1, 0, 1],
 [1, 1, 0, 1, 0, 1]]

In [14]:
# -----------
# User Instructions:
#
# Modify the the search function so that it becomes
# an A* search algorithm as defined in the previous
# lectures.
#
# Your function should return the expanded grid
# which shows, for each element, the count when
# it was expanded or -1 if the element was never expanded.
# 
# If there is no path from init to goal,
# the function should return the string 'fail'
# ----------

grid = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]
heuristic = [[9, 8, 7, 6, 5, 4],
             [8, 7, 6, 5, 4, 3],
             [7, 6, 5, 4, 3, 2],
             [6, 5, 4, 3, 2, 1],
             [5, 4, 3, 2, 1, 0]]

init = [0, 0]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['^', '<', 'v', '>']

def search(grid,init,goal,cost,heuristic):
    # ----------------------------------------
    # modify the code below
    # ----------------------------------------
    closed = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    closed[init[0]][init[1]] = 1

    expand = [[-1 for col in range(len(grid[0]))] for row in range(len(grid))]
    action = [[-1 for col in range(len(grid[0]))] for row in range(len(grid))]

    x = init[0]
    y = init[1]
    g = 0
    f=g+heuristic[x][y]
    open = [[f,g,heuristic[x][y], x, y]]

    found = False  # flag that is set when search is complete
    resign = False # flag set if we can't find expand
    count = 0
    
    while not found and not resign:
        if len(open) == 0:
            resign = True
            return "Fail"
        else:
            open.sort()
            open.reverse()
            next = open.pop()
            x = next[3]
            y = next[4]
            g = next[1]
            expand[x][y] = count
            count += 1
            
            if x == goal[0] and y == goal[1]:
                found = True
            else:
                for i in range(len(delta)):
                    x2 = x + delta[i][0]
                    y2 = y + delta[i][1]
                    if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                        if closed[x2][y2] == 0 and grid[x2][y2] == 0:
                            g2 = g + cost
                            open.append([g2+heuristic[x2][y2],g2,heuristic[x2][y2], x2, y2])
                            closed[x2][y2] = 1

    return expand
search(grid,init,goal,cost,heuristic)

[[0, -1, -1, -1, -1, -1],
 [1, -1, -1, -1, -1, -1],
 [2, -1, -1, -1, -1, -1],
 [3, -1, 8, 9, 10, 11],
 [4, 5, 6, 7, -1, 12]]

In [10]:
# ----------
# User Instructions:
# 
# Create a function compute_value which returns
# a grid of values. The value of a cell is the minimum
# number of moves required to get from the cell to the goal. 
#
# If a cell is a wall or it is impossible to reach the goal from a cell,
# assign that cell a value of 99.
# ----------

grid = [[0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 1, 0]]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1 # the cost associated with moving from a cell to an adjacent one

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['v', '>', '^', '<']

def compute_value(grid,goal,cost):
    # ----------------------------------------
    # insert code below
    # ----------------------------------------
    value = [[99 for col in range(len(grid[0]))] for row in range(len(grid))]
    policy = [[' ' for row in range(len(grid[0]))] for col in range(len(grid))]
    x=goal[0]
    y=goal[1]
    value[x][y]=0
    policy[x][y]='*'
    open = [[value[x][y], x, y]]
    
    while open:
        
        open.sort()
        open.reverse()
        next = open.pop()
        x = next[1]
        y = next[2]

        for i in range(len(delta)):
            x2 = x + delta[i][0]
            y2 = y + delta[i][1]
            if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                if value[x2][y2] == 99 and grid[x2][y2] == 0:
                    value[x2][y2] = value[x][y] + cost
                    policy[x2][y2]=delta_name[i]
                    open.append([value[x2][y2],x2, y2])
                
    
    # make sure your function returns a grid of values as 
    # demonstrated in the previous video.
    return policy 

In [11]:
compute_value(grid,goal,cost)

[['>', 'v', ' ', '>', '>', 'v'],
 ['>', 'v', ' ', '>', '>', 'v'],
 ['>', 'v', ' ', '>', '>', 'v'],
 ['>', '>', '>', '^', ' ', 'v'],
 ['^', '^', ' ', ' ', ' ', 'v'],
 ['^', '^', '<', '<', ' ', '*']]

In [12]:
# ----------
# User Instructions:
# 
# Write a function optimum_policy that returns
# a grid which shows the optimum policy for robot
# motion. This means there should be an optimum
# direction associated with each navigable cell from
# which the goal can be reached.
# 
# Unnavigable cells as well as cells from which 
# the goal cannot be reached should have a string 
# containing a single space (' '), as shown in the 
# previous video. The goal cell should have '*'.
# ----------

grid = [[0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]
init = [0, 0]
goal = [len(grid)-1, len(grid[0])-1]
cost = 1 # the cost associated with moving from a cell to an adjacent one

delta = [[-1, 0 ], # go up
         [ 0, -1], # go left
         [ 1, 0 ], # go down
         [ 0, 1 ]] # go right

delta_name = ['^', '<', 'v', '>']

def optimum_policy(grid,goal,cost):
    # ----------------------------------------
    # modify code below
    # ----------------------------------------
    value = [[99 for row in range(len(grid[0]))] for col in range(len(grid))]
    change = True
    policy = [[' ' for row in range(len(grid[0]))] for col in range(len(grid))]

    while change:
        change = False

        for x in range(len(grid)):
            for y in range(len(grid[0])):
                if goal[0] == x and goal[1] == y:
                    if value[x][y] > 0:
                        value[x][y] = 0

                        change = True

                elif grid[x][y] == 0:
                    for a in range(len(delta)):
                        x2 = x + delta[a][0]
                        y2 = y + delta[a][1]

                        if x2 >= 0 and x2 < len(grid) and y2 >= 0 and y2 < len(grid[0]) and grid[x2][y2] == 0:
                            v2 = value[x2][y2] + cost

                            if v2 < value[x][y]:
                                change = True
                                value[x][y] = v2

    return policy

In [8]:
forward = [[-1,  0], # go up
           [ 0, -1], # go left
           [ 1,  0], # go down
           [ 0,  1]] # go right
forward_name = ['up', 'left', 'down', 'right']
action = [-1, 0, 1]# action has 3 values: right turn, no turn, left turn
action_name = ['R', '#', 'L']
grid = [[1, 1, 1, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1, 1]]
init = [4, 3, 0] # given in the form [row,col,direction]
                 # direction = 0: up
                 #             1: left
                 #             2: down
                 #             3: right                
goal = [2, 0] # given in the form [row,col]
cost = [2, 1, 20] # cost has 3 values, corresponding to making # a right turn, no turn, and a left turn
def optimum_policy2D(grid,init,goal,cost):
    value = [[99 for col in range(len(grid[0]))] for row in range(len(grid))]
    heuristic = [[0 for col in range(len(grid[0]))] for row in range(len(grid))]
    policy = [[' ' for row in range(len(grid[0]))] for col in range(len(grid))]
    x=init[0]
    y=init[1]
    theta=init[2]
    value[x][y]=0
    heuristic[x][y]=abs(goal[0]-x)+abs(goal[1]-y)
    f=heuristic[x][y]+value[x][y]
    policy[goal[0]][goal[1]]='*'
    open = [[f,heuristic[x][y],value[x][y], x, y,theta]]
    while open:
        open.sort()
        open.reverse()
        next = open.pop()
        x = next[3]
        y = next[4]
        theta=next[5]
        for i in action:
            if theta==3 and i==1:
                theta2=0
            elif theta==0 and i==-1:
                theta2=3
            else:
                theta2=theta+i
            x2 = x + forward[theta2][0]
            y2 = y + forward[theta2][1]
            if x2 >= 0 and x2 < len(grid) and y2 >=0 and y2 < len(grid[0]):
                if grid[x2][y2] == 0:
                    if theta==theta2:
                        v2=value[x][y] + cost[1]
                        p=action_name[1]
                    else:
                        if (theta==0 and theta2==1)or(theta==1 and theta2==2)or(theta==2 and theta2==3)or(theta==3 and theta2==0):
                            v2=value[x][y] + cost[2]
                            p=action_name[2]
                        else:
                            v2=value[x][y] + cost[0]
                            p=action_name[0]
                    if v2 < value[x2][y2]:
                        value[x2][y2]=v2
                        policy[x][y]=p
                        heuristic[x2][y2]=abs(goal[0]-x2)+abs(goal[1]-y2)
                        f=heuristic[x2][y2]+value[x2][y2]
                        open.append([f,heuristic[x2][y2],value[x2][y2],x2, y2,theta2])
    return value

In [9]:
optimum_policy2D(grid,init,goal,cost)


[[99, 99, 99, 4, 6, 7],
 [99, 99, 99, 3, 99, 9],
 [24, 23, 22, 2, 4, 5],
 [99, 99, 99, 1, 99, 99],
 [99, 99, 99, 0, 99, 99]]

In [17]:
action = [-1, 0, 1]# action has 3 values: right turn, no turn, left turn
for i in action:
    print(i)


-1
0
1


In [3]:
def dist(s,e):
    return abs(s[0]-e[0])+abs(s[1]-e[1])
def astar():
    points=[[0,6],[0,2]]
    start=[0,0]

    f=0
    h=0
    g=0
    open=[[f,g,h,[start]]]
    path=[]
    while True:
        open.sort()
        open.reverse()
        next = open.pop()
        path=next[3].copy()
        for i in range(len(points)):
            if points[i] not in path:
                g=dist(path[len(path)-1],points[i])+next[1]
                h=0
                fpath=path.copy()
                fpath.append(points[i])
                for j in range(len(points)):
                    if points[j]not in fpath:
                        hj=dist(points[j],points[i])
                        if hj>h:
                            h=hj
                f=h+g
                open.append([f,g,h,fpath])
                if len(fpath)==len(points)+1:
                    return fpath
astar()       

[[0, 0], [0, 2], [0, 6]]

In [7]:
x=[[1,2],[3,4],[5,6]]
i=[2,2]
if i in x:
    print("hi")

In [15]:
start=[0,0]
open=[[[start]]]
path=[]
open.sort()
open.reverse()
next = open.pop()
path=next[0].copy()
path.append([2,3])

print(next[0])

[[0, 0]]


In [38]:
forward_name = ['up', 'left', 'down', 'right']
grid = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
        1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
roadWidth=3
potential=[255 for i in grid]
nx=32
ny=26
start=23*(nx)+1
open=[[0,start,forward_name[3]]]
potential[start]=0
goal=(nx)*11+29
def turnLeft(x,dire,costs,potential,roadWidth,goal):
    if dire==forward_name[0]:#up
        for i in range(int(3*roadWidth/2)):
            add(grid,potential,potential[x-(nx*i)-i],x-(nx*(i+1))-(i+1),forward_name[1],goal,True)
        add(grid,potential,potential[x-(nx*(i+1))-(i+1)],x-(nx*(i+1))-(i+2),forward_name[1],goal,False)
            
    if dire==forward_name[1]:#left
        for i in range(int(3*roadWidth/2)):
            add(grid,potential,potential[x+(nx*i)-i],x+(nx*(i+1))-(i+1),forward_name[2],goal,True)
        add(grid,potential,potential[x+(nx*(i+1))-(i+1)],x+(nx*(i+2))-(i+1),forward_name[2],goal,False)
            
    if dire==forward_name[2]:#down
        for i in range(int(3*roadWidth/2)):
            add(grid,potential,potential[x+(nx*i)+i],x+(nx*(i+1))+(i+1),forward_name[3],goal,True)
        add(grid,potential,potential[x+(nx*(i+1))+(i+1)],x+(nx*(i+1))+(i+2),forward_name[3],goal,False)
            
    if dire==forward_name[3]:#right
        for i in range(int(3*roadWidth/2)):
            add(grid,potential,potential[x-(nx*i)+i],x-(nx*(i+1))+(i+1),forward_name[0],goal,True)
        add(grid,potential,potential[x-(nx*(i+1))+(i+1)],x-(nx*(i+2))+(i+1),forward_name[0],goal,False)

def turnRight(x,dire,costs,potential,roadWidth,goal):
    if dire==forward_name[0]:#up
        for i in range(int(roadWidth/2)):
            add(grid,potential,potential[x-(nx*i)+i],x-(nx*(i+1))+(i+1),forward_name[3],goal,True)
        add(grid,potential,potential[x-(nx*(i+1))+(i+1)],x-(nx*(i+1))+(i+2),forward_name[3],goal,False)

    if dire==forward_name[1]:#left
        for i in range(int(roadWidth/2)):
            add(grid,potential,potential[x-(nx*i)-i],x-(nx*(i+1))-(i+1),forward_name[0],goal,True)
        add(grid,potential,potential[x-(nx*(i+1))-(i+1)],x-(nx*(i+2))-(i+1),forward_name[0],goal,False)
            
    if dire==forward_name[2]:#down
        for i in range(int(roadWidth/2)):
            add(grid,potential,potential[x+(nx*i)-i],x+(nx*(i+1))-(i+1),forward_name[1],goal,True)
        add(grid,potential,potential[x+(nx*(i+1))-(i+1)],x+(nx*(i+1))-(i+2),forward_name[1],goal,False)
        
    if dire==forward_name[3]:#right
        for i in range(int(roadWidth/2)):
            add(grid,potential,potential[x+(nx*i)+i],x+(nx*(i+1))+(i+1),forward_name[2],goal,True)
        add(grid,potential,potential[x+(nx*(i+1))+(i+1)],x+(nx*(i+2))+(i+1),forward_name[2],goal,False)

def add(grid,potential,prev_Potential,next_i,dire,end,turn):
    if next_i<0 or next_i>nx*ny:
        return 0
    if potential[next_i]<255:
        return 0
    if grid[next_i]==1 :
        return 0
    potential[next_i]=calc_potential(potential,grid[next_i]+1,next_i,prev_Potential)
    grid[next_i]=2
    if turn==False:
        x=next_i%nx
        y=next_i/nx
        xg=end%nx
        yg=end/nx
        dist=abs(xg-x)+abs(yg-y)
        open.append([dist+ potential[next_i],next_i,dire])
    
def calc_potential(potential,n,next_i,prev_Potential):
    minVal=255
    for i in [-1,0,1]:
        for j in [-1,0,1]:
            if minVal>potential[next_i+i+nx*j]:
                minVal=potential[next_i+i+nx*j]
    
    return minVal+n
    
    
def calc_potentials(grid,open,goal,potential,roadWidth):
    turnRightFlag=0
    turnFlagL=0
    turnFlagR=0    
    turnLeftFlag=0
    while open:
        open.sort()
        open.reverse()
        next = open.pop()
        i=next[1]
        h=next[2]
        if(i==goal):
#            print(potential)
            break
        if h==forward_name[3]:#right
            add(grid,potential,potential[i],i+1,h,goal,False)
            for j in range(3):
                if(grid[i+(int(roadWidth/2)+j)*nx]==1):
                    turnRightFlag=0
                    turnFlagR=0
                    break
                else:
                    turnRightFlag=1
            if turnRightFlag==1 and turnFlagR==0:
                turnRight(i,h,grid,potential,roadWidth,goal)
                turnFlagR=1
            for j in range(3):
                if(grid[i-(int(3*roadWidth/2)+j)*nx]==1):
                    turnLeftFlag=0
                    turnFlagL=0
                    break
                else:
                    turnLeftFlag=1
            if turnLeftFlag==1 and turnFlagL==0:
                turnLeft(i,h,grid,potential,roadWidth,goal)
                turnFlagL=1
        if h==forward_name[2]:#down
            add(grid,potential,potential[i],i+nx,h,goal,False)
            for j in range(3):
                if(grid[i-(int(roadWidth/2)+j)]==1):
                    turnRightFlag=0
                    turnFlagR=0
                    break
                else:
                    turnRightFlag=1
                if turnRightFlag==1 and turnFlagR==0:
                    turnRight(i,h,grid,potential,roadWidth,goal)
                    turnFlagR=1
            for j in range(3):
                if(grid[i+(int(3*roadWidth/2)+j)]==1):
                    turnLeftFlag=0
                    turnFlagL=0
                    break
                else:
                    turnLeftFlag=1
            if turnLeftFlag==1 and turnFlagL==0:
                turnLeft(i,h,grid,potential,roadWidth,goal)
                turnFlagL=1
        if h==forward_name[1]:#left
            add(grid,potential,potential[i],i-1,h,goal,False)
            for j in range(3):
                if(grid[i-(int(roadWidth/2)+j)*nx]==1):
                    turnRightFlag=0
                    turnFlagR=0
                    break
                else:
                    turnRightFlag=1
                if turnRightFlag==1 and turnFlagR==0:
                    turnRight(i,h,grid,potential,roadWidth,goal)
                    turnFlagR=1
            for j in range(3):
                if(grid[i+(int(3*roadWidth/2)+j)*nx]==1):
                    turnLeftFlag=0
                    turnFlagL=0
                    break
                else:
                    turnLeftFlag=1
            if turnLeftFlag==1 and turnFlagL==0:
                turnLeft(i,h,grid,potential,roadWidth,goal)
                turnFlagL=1
        if h==forward_name[0]:#up
            add(grid,potential,potential[i],i-nx,h,goal,False)
            for j in range(3):
                if(grid[i+(int(roadWidth/2)+j)]==1):
                    turnRightFlag=0
                    turnFlagR=0
                    break
                else:
                    turnRightFlag=1
            if turnRightFlag==1 and turnFlagR==0:
                turnRight(i,h,grid,potential,roadWidth,goal)
                turnFlagR=1
            for j in range(3):
                if(grid[i-(int(3*roadWidth/2)+j)]==1):
                    turnLeftFlag=0
                    turnFlagL=0
                    break
                else:
                    turnLeftFlag=1
            if turnLeftFlag==1 and turnFlagL==0:
                turnLeft(i,h,grid,potential,roadWidth,goal)
                turnFlagL=1
calc_potentials(grid,open,goal,potential,roadWidth)
grid[start]=3
grid[goal]=3
print(grid)


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 

In [6]:
cel=[['#',' ','#'],
     ['#','#','#'],
     ['#','*','#']]

In [34]:
for i in range(ny):
    print(potential[0+i*nx:nx+i*nx])
#    print(grid[0+i*nx:nx+i*nx])

[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]
[255, 255, 255, 255, 255, 255, 255

In [39]:
for i in range(ny):
#    print(potential[0+i*nx:nx+i*nx])
    print(grid[0+i*nx:nx+i*nx])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 2,